AllCops:
  TargetRubyVersion: 2.3

Style/StringLiterals:
  EnforcedStyle: double_quotes

LineLength:
  Max: 119 # github diff (ex. +-)

Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Max: 30
